[[nodes]]
node_id = 0
position = [6.0, 0.0, 0.0]
nodes = [1, 2, 3, 4, 5, 6, 7, 8, 9]

[[nodes]]
node_id = 1
position = [12.0, 0.0, 0.0]
nodes = [0, 2, 3, 4, 5, 6, 7, 8, 9]

[[nodes]]
node_id = 2
position = [18.0, 0.0, 0.0]
nodes = [0, 1, 3, 4, 5, 6, 7, 8, 9]

[[nodes]]
node_id = 3
position = [18.0, -6.0, 0.0]
nodes = [0, 1, 2, 4, 5, 6, 7, 8, 9]

[[nodes]]
node_id = 4
position = [18.0, -12.0, 0.0]
nodes = [0, 1, 2, 3, 5, 6, 7, 8, 9]

[[nodes]]
node_id = 5
position = [18.0, -18.0, 0.0]
nodes = [0, 1, 2, 3, 4, 6, 7, 8, 9]

[[nodes]]
node_id = 6
position = [12.0, -18.0, 0.0]
nodes = [0, 1, 2, 3, 4, 5, 7, 8, 9]

[[nodes]]
node_id = 7
position = [6.0, -18.0, 0.0]
nodes = [0, 1, 2, 3, 4, 5, 6, 8, 9]

[[nodes]]
node_id = 8
position = [0.0, -18.0, 0.0]
nodes = [0, 1, 2, 3, 4, 5, 6, 7, 9]

[[nodes]]
node_id = 9
position = [0.0, -12.0, 0.0]
nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8]
