[[nodes]]
node_id = 0
position = [6.0, 0.0, 0.0]
nodes = [1, 14]

[[nodes]]
node_id = 1
position = [12.0, 0.0, 0.0]
nodes = [0, 2]

[[nodes]]
node_id = 2
position = [18.0, 0.0, 0.0]
nodes = [1, 3]

[[nodes]]
node_id = 3
position = [24.0, 0.0, 0.0]
nodes = [2, 4]

[[nodes]]
node_id = 4
position = [24.0, -6.0, 0.0]
nodes = [3, 5]

[[nodes]]
node_id = 5
position = [24.0, -12.0, 0.0]
nodes = [4, 6]

[[nodes]]
node_id = 6
position = [24.0, -18.0, 0.0]
nodes = [5, 7]

[[nodes]]
node_id = 7
position = [24.0, -24.0, 0.0]
nodes = [6, 8]

[[nodes]]
node_id = 8
position = [18.0, -24.0, 0.0]
nodes = [7, 9]

[[nodes]]
node_id = 9
position = [12.0, -24.0, 0.0]
nodes = [8, 10]

[[nodes]]
node_id = 10
position = [6.0, -24.0, 0.0]
nodes = [9, 11]

[[nodes]]
node_id = 11
position = [0.0, -24.0, 0.0]
nodes = [10, 12]

[[nodes]]
node_id = 12
position = [0.0, -18.0, 0.0]
nodes = [11, 13]

[[nodes]]
node_id = 13
position = [0.0, -12.0, 0.0]
nodes = [12, 14]

[[nodes]]
node_id = 14
position = [0.0, -6.0, 0.0]
nodes = [0, 13]
